### PR TITLE
Rewrite for handling external SQL

### PR DESCRIPTION
**Pull request by thermokarst**
The idea here is to pull a bunch of the data handling and SQL schema jazz out of the main python scripts, and put them in a more appropriate location. A side-effect is that it should be more clear to follow.

### CODE REVIEW

**Comment by thermokarst** [comment]
@mkbrk: this is a first cut based on our prior discussion, just a gross refactor. let me know what you think. thanks!

**Comment by mkbrk** [comment]
@thermokarst I like how you organized it! Makes a lot of sense to me.

**Comment by thermokarst** [comment]
Thanks, your suggestions were instrumental for the refactor. If this seems like an appropriate merge to you, then I vote for merging the PR and getting this into master. Otherwise, we can stew on it a bit longer if you want.

**Comment by mkbrk** [comment]
No, seems like a good merge to me.

**Pull request merged**
